In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/sandeepmj/datasets/refs/heads/main/diamonds.csv")

       carat diamond cut color clarity  depth  table  price     x     y     z
0       0.23       Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21     Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23        Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29     Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31        Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...         ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72       Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72        Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70   Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86     Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75       Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [4]:
df.head

<bound method NDFrame.head of        carat diamond cut color clarity  depth  table  price     x     y     z
0       0.23       Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21     Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23        Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29     Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31        Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...         ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72       Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72        Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70   Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86     Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75       Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]>

In [5]:
df.head (10)

   carat diamond cut color clarity  depth  table  price     x     y     z
0   0.23       Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21     Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23        Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29     Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31        Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
5   0.24   Very Good     J    VVS2   62.8   57.0    336  3.94  3.96  2.48
6   0.24   Very Good     I    VVS1   62.3   57.0    336  3.95  3.98  2.47
7   0.26   Very Good     H     SI1   61.9   55.0    337  4.07  4.11  2.53
8   0.22        Fair     E     VS2   65.1   61.0    337  3.87  3.78  2.49
9   0.23   Very Good     H     VS1   59.4   61.0    338  4.00  4.05  2.39

In [6]:
df.tail (10)

       carat diamond cut color clarity  depth  table  price     x     y     z
53930   0.71     Premium     E     SI1   60.5   55.0   2756  5.79  5.74  3.49
53931   0.71     Premium     F     SI1   59.8   62.0   2756  5.74  5.73  3.43
53932   0.70   Very Good     E     VS2   60.5   59.0   2757  5.71  5.76  3.47
53933   0.70   Very Good     E     VS2   61.2   59.0   2757  5.69  5.72  3.49
53934   0.72     Premium     D     SI1   62.7   59.0   2757  5.69  5.73  3.58
53935   0.72       Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72        Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70   Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86     Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75       Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

In [7]:
df.sample

<bound method NDFrame.sample of        carat diamond cut color clarity  depth  table  price     x     y     z
0       0.23       Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21     Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23        Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29     Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31        Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...         ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72       Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72        Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70   Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86     Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75       Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]>

In [8]:
df.info

<bound method DataFrame.info of        carat diamond cut color clarity  depth  table  price     x     y     z
0       0.23       Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21     Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23        Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29     Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31        Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...         ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72       Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72        Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70   Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86     Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75       Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]>

In [9]:
df.color

0        E
1        E
2        E
3        I
4        J
        ..
53935    D
53936    D
53937    D
53938    H
53939    D
Name: color, Length: 53940, dtype: str

In [10]:
df.carat

0        0.23
1        0.21
2        0.23
3        0.29
4        0.31
         ...
53935    0.72
53936    0.72
53937    0.70
53938    0.86
53939    0.75
Name: carat, Length: 53940, dtype: float64

In [11]:
type(df.carat)

pandas.Series

In [12]:
df.carat * 2

0        0.46
1        0.42
2        0.46
3        0.58
4        0.62
         ...
53935    1.44
53936    1.44
53937    1.40
53938    1.72
53939    1.50
Name: carat, Length: 53940, dtype: float64

In [13]:
df * 2

,carat,diamond cut,color,clarity,depth,table,price,x,y,z
0,0.46,IdealIdeal,EE,SI2SI2,123.0,110.0,652,7.90,7.96,4.86
1,0.42,PremiumPremium,EE,SI1SI1,119.6,122.0,652,7.78,7.68,4.62
2,0.46,GoodGood,EE,VS1VS1,113.8,130.0,654,8.10,8.14,4.62
3,0.58,PremiumPremium,II,VS2VS2,124.8,116.0,668,8.40,8.46,5.26
4,0.62,GoodGood,JJ,SI2SI2,126.6,116.0,670,8.68,8.70,5.50
...,...,...,...,...,...,...,...,...,...,...
53935,1.44,IdealIdeal,DD,SI1SI1,121.6,114.0,5514,11.50,11.52,7.00
53936,1.44,GoodGood,DD,SI1SI1,126.2,110.0,5514,11.38,11.50,7.22
53937,1.40,Very GoodVery Good,DD,SI1SI1,125.6,120.0,5514,11.32,11.36,7.12
53938,1.72,PremiumPremium,HH,SI2SI2,122.0,116.0,5514,12.30,12.24,7.48
53939,1.50,IdealIdeal,DD,SI2SI2,124.4,110.0,5514,11.66,11.74,7.28

In [14]:
df.head

<bound method NDFrame.head of        carat diamond cut color clarity  depth  table  price     x     y     z
0       0.23       Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21     Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23        Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29     Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31        Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...         ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72       Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72        Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70   Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86     Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75       Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]>

In [15]:
df.diamond cut

SyntaxError: invalid syntax (626455472.py, line 1)

In [16]:
df["diamond cut"]

0            Ideal
1          Premium
2             Good
3          Premium
4             Good
           ...
53935        Ideal
53936         Good
53937    Very Good
53938      Premium
53939        Ideal
Name: diamond cut, Length: 53940, dtype: str

In [17]:
df.head

<bound method NDFrame.head of        carat diamond cut color clarity  depth  table  price     x     y     z
0       0.23       Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21     Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23        Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29     Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31        Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...         ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72       Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72        Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70   Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86     Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75       Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]>

In [18]:
df["diamond cut"].unique()

<StringArray>
['Ideal', 'Premium', 'Good', 'Very Good', 'Fair']
Length: 5, dtype: str

In [ ]:
##there are 5 unique diamond cut v