# Calculating Across Rows

How do we calculate row-wise in Pandas like we do in Excel?

<img src="https://sandeepmj.github.io/image-host/oil-v-gold.png">

We need a couple of new concepts to do this calculation:

1. Capture a number from a cell and hold in variable.
2. We `apply()`calculations across columns, row-wise, using using a `lambda expression`.


This is step one in your ability to accomplish tasks that are highly specialized to your beats.

In [7]:
## import library
import pandas as pd

In [8]:
## pull in data
df = pd.read_csv("https://raw.githubusercontent.com/sandeepmj/datasets/refs/heads/main/oil-v-gold-pandas.csv")

In [9]:
df.head(5)

      Date  PX_GOLD  PX_OIL
0  1/31/08    922.7   91.75
1  2/29/08    975.0  101.84
2  3/31/08    916.2  101.58
3  4/30/08    865.1  113.46
4  5/30/08    887.3  127.35

What are the different values for row **TWO** in this formula for `PX_GOLD`:

$$\text{Pct Chg at time } t = \frac{\text{Value at time } t - \text{Value at start time}}{\text{Value at start time}} \times 100$$

Use `.iat` to store a value from a specific cell into a variable:

```dataframe["column_name"].iat[row_index_number]```

In [10]:
## hold gold
df ["PX_GOLD"].iat[0]

np.float64(922.7)

Also works:

`dataframe.iat[col_index_number, row_index_number]`

In [11]:
## hold gold col index, row index
gold_start = df.iat [0,1]
gold_start

np.float64(922.7)

Place the value for the starting oil price in a variable called `oil_baseline`

In [12]:
## oil_baseline
oil_start = df.iat [0,2]
oil_start

np.float64(91.75)

# `lambda expressions`

We're going to just write one first and then break it down:

In [13]:
## create a new column that holds the zero index for gold
df["gold_zero_index"] = df["PX_GOLD"].apply(lambda x:(x-gold_start)/gold_start * 100 )
df

         Date  PX_GOLD  PX_OIL  gold_zero_index
0     1/31/08    922.7   91.75         0.000000
1     2/29/08    975.0  101.84         5.668148
2     3/31/08    916.2  101.58        -0.704454
3     4/30/08    865.1  113.46        -6.242549
4     5/30/08    887.3  127.35        -3.836567
..        ...      ...     ...              ...
116   9/29/17   1281.5   51.67        38.885878
117  10/31/17   1270.5   54.38        37.693725
118  11/30/17   1273.2   57.40        37.986344
119  12/29/17   1309.3   60.42        41.898775
120   1/31/18   1339.0   64.73        45.117590

[121 rows x 4 columns]

## What  `x` stand for:

- In Pandas, we `apply()` lambda expressions to columns.
-  `.apply()`  works element-wise on each value in the `PX_GOLD` column, one at a time.
- `x` is a single value representing a cell in the column `PX_GOLD`
- The ```lambda x:``` processes each row of a dataframe, one row at a time.
-  The `lambda expression` takes each individual number `x` from `PX_GOLD` and runs the indexing formula on it.

Think of it as: "call each value in `PX_GOLD` as `x`, and do this math to using `x` in the formula."

## create a new column that holds the zero index for oil

In [14]:
## zero index oil
df["oil_zero_index"] = df["PX_OIL"].apply(lambda x:(x-oil_start)/oil_start * 100 )
df

         Date  PX_GOLD  PX_OIL  gold_zero_index  oil_zero_index
0     1/31/08    922.7   91.75         0.000000        0.000000
1     2/29/08    975.0  101.84         5.668148       10.997275
2     3/31/08    916.2  101.58        -0.704454       10.713896
3     4/30/08    865.1  113.46        -6.242549       23.662125
4     5/30/08    887.3  127.35        -3.836567       38.801090
..        ...      ...     ...              ...             ...
116   9/29/17   1281.5   51.67        38.885878      -43.683924
117  10/31/17   1270.5   54.38        37.693725      -40.730245
118  11/30/17   1273.2   57.40        37.986344      -37.438692
119  12/29/17   1309.3   60.42        41.898775      -34.147139
120   1/31/18   1339.0   64.73        45.117590      -29.449591

[121 rows x 5 columns]

In [15]:
## call df

### 100-indexing

Create cells below to add columns for both oil and gold for 100-indexing.

Reminder, the formula for 100-indexing:

$$\text{Index} = \left(\frac{\text{value at time } t}{\text{value at start}}\right) \times 100$$

In [16]:
## gold 100
df["gold_100_index"] = df["PX_GOLD"].apply(lambda x:(x/gold_start) * 100 )
df

,Date,PX_GOLD,PX_OIL,gold_zero_index,oil_zero_index,gold_100_index
0,1/31/08,922.7,91.75,0.000000,0.000000,100.000000
1,2/29/08,975.0,101.84,5.668148,10.997275,105.668148
2,3/31/08,916.2,101.58,-0.704454,10.713896,99.295546
3,4/30/08,865.1,113.46,-6.242549,23.662125,93.757451
4,5/30/08,887.3,127.35,-3.836567,38.801090,96.163433
...,...,...,...,...,...,...
116,9/29/17,1281.5,51.67,38.885878,-43.683924,138.885878
117,10/31/17,1270.5,54.38,37.693725,-40.730245,137.693725
118,11/30/17,1273.2,57.40,37.986344,-37.438692,137.986344
119,12/29/17,1309.3,60.42,41.898775,-34.147139,141.898775
120,1/31/18,1339.0,64.73,45.117590,-29.449591,145.117590

In [17]:
##round the above 
df["gold_100_index"] = df["PX_GOLD"].apply(lambda x: round(x/gold_start * 100,1 ))
df

,Date,PX_GOLD,PX_OIL,gold_zero_index,oil_zero_index,gold_100_index
0,1/31/08,922.7,91.75,0.000000,0.000000,100.0
1,2/29/08,975.0,101.84,5.668148,10.997275,105.7
2,3/31/08,916.2,101.58,-0.704454,10.713896,99.3
3,4/30/08,865.1,113.46,-6.242549,23.662125,93.8
4,5/30/08,887.3,127.35,-3.836567,38.801090,96.2
...,...,...,...,...,...,...
116,9/29/17,1281.5,51.67,38.885878,-43.683924,138.9
117,10/31/17,1270.5,54.38,37.693725,-40.730245,137.7
118,11/30/17,1273.2,57.40,37.986344,-37.438692,138.0
119,12/29/17,1309.3,60.42,41.898775,-34.147139,141.9
120,1/31/18,1339.0,64.73,45.117590,-29.449591,145.1

In [18]:
## oil 100
df["oil_100_index"] = df["PX_OIL"].apply(lambda x: (x/oil_start) * 100 )
df

,Date,PX_GOLD,PX_OIL,gold_zero_index,oil_zero_index,gold_100_index,oil_100_index
0,1/31/08,922.7,91.75,0.000000,0.000000,100.0,100.000000
1,2/29/08,975.0,101.84,5.668148,10.997275,105.7,110.997275
2,3/31/08,916.2,101.58,-0.704454,10.713896,99.3,110.713896
3,4/30/08,865.1,113.46,-6.242549,23.662125,93.8,123.662125
4,5/30/08,887.3,127.35,-3.836567,38.801090,96.2,138.801090
...,...,...,...,...,...,...,...
116,9/29/17,1281.5,51.67,38.885878,-43.683924,138.9,56.316076
117,10/31/17,1270.5,54.38,37.693725,-40.730245,137.7,59.269755
118,11/30/17,1273.2,57.40,37.986344,-37.438692,138.0,62.561308
119,12/29/17,1309.3,60.42,41.898775,-34.147139,141.9,65.852861
120,1/31/18,1339.0,64.73,45.117590,-29.449591,145.1,70.550409

# Homework

<a href="https://raw.githubusercontent.com/sandeepmj/datasets/refs/heads/main/demo-data-solutions/cablebill-v-income.csv">This dataset</a> shows the price of a standard cable subscription and the U.S. median income annually between 1995-2023.

Has median income kept pace with the price of a cable subscription?

Round all numbers to 1 decimal place

In [19]:
## read file
import pandas as pd

In [34]:
## get info
df = pd.read_csv("https://raw.githubusercontent.com/sandeepmj/datasets/refs/heads/main/demo-data-solutions/cablebill-v-income.csv")

In [35]:
df.info

<bound method DataFrame.info of     year  avg_cable_bill  median_household_income
0   1995           22.35                    35249
1   1996           23.28                    36689
2   1997           26.31                    38229
3   1998           27.88                    40148
4   1999           28.94                    41994
5   2000           31.22                    42349
6   2001           33.75                    42710
7   2002           36.47                    43057
8   2003           38.95                    43564
9   2004           41.04                    44684
10  2005           43.04                    46242
11  2006           43.26                    48451
12  2007           47.27                    50740
13  2008           49.65                    52029
14  2009           52.37                    50221
15  2010           54.44                    50046
16  2011           57.46                    50502
17  2012           61.63                    51371
18  2013           69.18                    52250
19  2014           71.45                    53657
20  2015           78.42                    55775
21  2016          150.98                    57617
22  2017          168.49                    61372
23  2018          199.99                    64324
24  2019          210.84                    69560
25  2020          217.42                    67521
26  2021          231.10                    70784
27  2022          251.48                    74580
28  2023          291.81                    75143>

In [36]:
df.head(29)

    year  avg_cable_bill  median_household_income
0   1995           22.35                    35249
1   1996           23.28                    36689
2   1997           26.31                    38229
3   1998           27.88                    40148
4   1999           28.94                    41994
5   2000           31.22                    42349
6   2001           33.75                    42710
7   2002           36.47                    43057
8   2003           38.95                    43564
9   2004           41.04                    44684
10  2005           43.04                    46242
11  2006           43.26                    48451
12  2007           47.27                    50740
13  2008           49.65                    52029
14  2009           52.37                    50221
15  2010           54.44                    50046
16  2011           57.46                    50502
17  2012           61.63                    51371
18  2013           69.18                    52250
19  2014           71.45                    53657
20  2015           78.42                    55775
21  2016          150.98                    57617
22  2017          168.49                    61372
23  2018          199.99                    64324
24  2019          210.84                    69560
25  2020          217.42                    67521
26  2021          231.10                    70784
27  2022          251.48                    74580
28  2023          291.81                    75143

### Index cable billl

In [23]:
##index cable bill

In [37]:
cable_base = df["avg_cable_bill"].iat[0]
cable_base

np.float64(22.35)

In [38]:
cable_base = df.iat [0,1]

In [40]:
df["avg_cable_bill"] = df["avg_cable_bill"].apply(lambda x: (x - cable_base) / cable_base * 100)
print(df)

    year  avg_cable_bill  median_household_income
0   1995        0.000000                    35249
1   1996        4.161074                    36689
2   1997       17.718121                    38229
3   1998       24.742729                    40148
4   1999       29.485459                    41994
5   2000       39.686801                    42349
6   2001       51.006711                    42710
7   2002       63.176734                    43057
8   2003       74.272931                    43564
9   2004       83.624161                    44684
10  2005       92.572707                    46242
11  2006       93.557047                    48451
12  2007      111.498881                    50740
13  2008      122.147651                    52029
14  2009      134.317673                    50221
15  2010      143.579418                    50046
16  2011      157.091723                    50502
17  2012      175.749441                    51371
18  2013      209.530201                    52250
19  2014      219.686801                    53657
20  2015      250.872483                    55775
21  2016      575.525727                    57617
22  2017      653.870246                    61372
23  2018      794.809843                    64324
24  2019      843.355705                    69560
25  2020      872.796421                    67521
26  2021      934.004474                    70784
27  2022     1025.190157                    74580
28  2023     1205.637584                    75143

### Index median income

In [41]:
## income_baseline
income_base = df["median_household_income"].iat[0]
income_base

np.int64(35249)

In [42]:
income_base = df.iat [0,2]

In [43]:
## median income index
df ["median_household_income"] = df ["median_household_income"].apply(lambda x: (x-income_base)/ income_base * 100)
print(df)

    year  avg_cable_bill  median_household_income
0   1995        0.000000                 0.000000
1   1996        4.161074                 4.085222
2   1997       17.718121                 8.454141
3   1998       24.742729                13.898267
4   1999       29.485459                19.135295
5   2000       39.686801                20.142415
6   2001       51.006711                21.166558
7   2002       63.176734                22.150983
8   2003       74.272931                23.589322
9   2004       83.624161                26.766717
10  2005       92.572707                31.186700
11  2006       93.557047                37.453545
12  2007      111.498881                43.947346
13  2008      122.147651                47.604187
14  2009      134.317673                42.474964
15  2010      143.579418                41.978496
16  2011      157.091723                43.272150
17  2012      175.749441                45.737468
18  2013      209.530201                48.231155
19  2014      219.686801                52.222758
20  2015      250.872483                58.231439
21  2016      575.525727                63.457119
22  2017      653.870246                74.109904
23  2018      794.809843                82.484609
24  2019      843.355705                97.338932
25  2020      872.796421                91.554370
26  2021      934.004474               100.811371
27  2022     1025.190157               111.580470
28  2023     1205.637584               113.177679

## analysis

It seems like the average cable bill has outpaced the median household income by double from 1997-2001, then dramatically outpaced the median household income after 2002. There was a 165% difference between the average cable bill and median household income from 2002 to 2023.