# Sorting, Counting, Querying

We often have a large dataset but we are only interested in smaller sections of it.

Or we want to sort from largest to smallest.

Or perhaps we want to know how many instances of some value there is in the data.

Tonight we finally move beyond the basics to see the start of data analysis.

## Import libraries

In [37]:
## import libraries
import pandas as pd

## Upload Olympics datasets to this notebook.

### Import ```olympics-summer.csv``` and store in a dataframe called ```dfs``` (<a href="https://raw.githubusercontent.com/sandeepmj/datasets/main/olympics-summer.csv">link</a>).


### Import ```olympics-winter.csv``` and store in a dataframe called ```dfw``` (<a href="https://raw.githubusercontent.com/sandeepmj/datasets/main/olympics-winter.csv">link</a>).

In [38]:
## import summer data
dfs = pd.read_csv("https://raw.githubusercontent.com/sandeepmj/datasets/main/olympics-summer.csv")
dfs

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal
0,1724,Aristidis Akratopoulos,M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Tennis,Tennis Men's Singles,NaN
1,1724,Aristidis Akratopoulos,M,NaN,NaN,NaN,Greece-3,GRE,1896,Athina,Tennis,Tennis Men's Doubles,NaN
2,1725,"Konstantinos ""Kostas"" Akratopoulos",M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Tennis,Tennis Men's Singles,NaN
3,1725,"Konstantinos ""Kostas"" Akratopoulos",M,NaN,NaN,NaN,Greece-3,GRE,1896,Athina,Tennis,Tennis Men's Doubles,NaN
4,4113,Anastasios Andreou,M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Athletics,Athletics Men's 110 metres Hurdles,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
222547,135528,Marc Zwiebler,M,32.0,181.0,75.0,Germany,GER,2016,Rio de Janeiro,Badminton,Badminton Men's Singles,NaN
222548,135547,Viktoriya Viktorovna Zyabkina,F,23.0,174.0,62.0,Kazakhstan,KAZ,2016,Rio de Janeiro,Athletics,Athletics Women's 100 metres,NaN
222549,135547,Viktoriya Viktorovna Zyabkina,F,23.0,174.0,62.0,Kazakhstan,KAZ,2016,Rio de Janeiro,Athletics,Athletics Women's 200 metres,NaN
222550,135547,Viktoriya Viktorovna Zyabkina,F,23.0,174.0,62.0,Kazakhstan,KAZ,2016,Rio de Janeiro,Athletics,Athletics Women's 4 x 100 metres Relay,NaN
222551,135568,Olga Igorevna Zyuzkova,F,33.0,171.0,69.0,Belarus,BLR,2016,Rio de Janeiro,Basketball,Basketball Women's Basketball,NaN

In [39]:
dfs["Medal"].unique()

<StringArray>
[nan, 'Silver', 'Gold', 'Bronze']
Length: 4, dtype: str

In [40]:
## import winter data
dfw = pd.read_csv("https://raw.githubusercontent.com/sandeepmj/datasets/main/olympics-winter.csv")
dfw

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal
0,391,Clarence John Abel,M,23.0,185.0,102.0,United States,USA,1924,Chamonix,Ice Hockey,Ice Hockey Men's Ice Hockey,Silver
1,992,Josef Adolf,M,25.0,NaN,NaN,Czechoslovakia,TCH,1924,Chamonix,Nordic Combined,Nordic Combined Men's Individual,NaN
2,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Ski Jumping,"Ski Jumping Men's Normal Hill, Individual",NaN
3,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Cross Country Skiing,Cross Country Skiing Men's 18 kilometres,NaN
4,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Nordic Combined,Nordic Combined Men's Individual,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
48559,135485,Stepan Olegovich Zuyev,M,25.0,189.0,90.0,Russia,RUS,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN
48560,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN
48561,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN
48562,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN
48563,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN

## Get a sense of the data

In [41]:
## SUMMER
## what exactly do we have: columns, datatypes, etc.
dfs.info()

<class 'pandas.DataFrame'>
RangeIndex: 222552 entries, 0 to 222551
Data columns (total 13 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   ID            222552 non-null  int64
 1   Athlete Name  222552 non-null  str
 2   Sex           222552 non-null  str
 3   Age           213363 non-null  float64
 4   Height        170695 non-null  float64
 5   Weight        168698 non-null  float64
 6   Team          222552 non-null  str
 7   NOC           222552 non-null  str
 8   Year          222552 non-null  int64
 9   City          222552 non-null  str
 10  Sport         222552 non-null  str
 11  Event         222552 non-null  str
 12  Medal         34088 non-null   str
dtypes: float64(3), int64(2), str(8)
memory usage: 22.1 MB

In [42]:
## WINTER
## what exactly do we have: columns, datatypes, etc.
dfw.info()

<class 'pandas.DataFrame'>
RangeIndex: 48564 entries, 0 to 48563
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID            48564 non-null  int64
 1   Athlete Name  48564 non-null  str
 2   Sex           48564 non-null  str
 3   Age           48279 non-null  float64
 4   Height        40250 non-null  float64
 5   Weight        39543 non-null  float64
 6   Team          48564 non-null  str
 7   NOC           48564 non-null  str
 8   Year          48564 non-null  int64
 9   City          48564 non-null  str
 10  Sport         48564 non-null  str
 11  Event         48564 non-null  str
 12  Medal         5695 non-null   str
dtypes: float64(3), int64(2), str(8)
memory usage: 4.8 MB

## Subsetting dataframes into smaller, targeted dataframes

When you subset a dataframe, you are filtering down based on selecting specific columns. We want to winnow a large dataset to manageable size by including only relevant columns.

There are two ways of doing this. One simple method is very common (you'll see many people use it), but the other method (also simple) is way more powerful and flexible.

### Method 1 - Pass a list of multiple column headers, it returns dataframe with only those columns
This is like calling a series (```df["Year"]```), but multiple columns:

####  ```df[["Column 1", "Column 2"]]```

In [43]:
## Create a dataframe that for only summer games years and cities
subset_of_full_data_df = dfw[["Year", "City", "Sport"]]
subset_of_full_data_df

       Year      City                 Sport
0      1924  Chamonix            Ice Hockey
1      1924  Chamonix       Nordic Combined
2      1924  Chamonix           Ski Jumping
3      1924  Chamonix  Cross Country Skiing
4      1924  Chamonix       Nordic Combined
...     ...       ...                   ...
48559  2014     Sochi         Alpine Skiing
48560  2014     Sochi         Alpine Skiing
48561  2014     Sochi         Alpine Skiing
48562  2014     Sochi           Ski Jumping
48563  2014     Sochi           Ski Jumping

[48564 rows x 3 columns]

## Sorting by single value

```dataframe.sort_values(by="Value 1", ascending = True)``` for A-Z or smaller numbers to bigger numbers

```ascending = False``` for Z-A or bigger to smaller numbers.

In [44]:
## sort by athlete names A-Z for winter olympics
dfw.sort_values(by="City")

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal
20978,15276,Mario Brodmann,M,25.0,176.0,80.0,Switzerland,SUI,1992,Albertville,Ice Hockey,Ice Hockey Men's Ice Hockey,NaN
21994,57092,Axel Kammerer,M,27.0,181.0,88.0,Germany,GER,1992,Albertville,Ice Hockey,Ice Hockey Men's Ice Hockey,NaN
21993,57070,Jiro Kamiharako,M,25.0,176.0,64.0,Japan,JPN,1992,Albertville,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN
21992,57070,Jiro Kamiharako,M,25.0,176.0,64.0,Japan,JPN,1992,Albertville,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN
21991,57070,Jiro Kamiharako,M,25.0,176.0,64.0,Japan,JPN,1992,Albertville,Ski Jumping,"Ski Jumping Men's Normal Hill, Individual",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
42206,93242,Lucia Peretti,F,19.0,163.0,50.0,Italy,ITA,2010,Vancouver,Short Track Speed Skating,"Short Track Speed Skating Women's 3,000 metres...",NaN
42207,93472,Rok Perko,M,24.0,186.0,93.0,Slovenia,SLO,2010,Vancouver,Alpine Skiing,Alpine Skiing Men's Downhill,NaN
42208,93479,Curdin Perl,M,25.0,181.0,74.0,Switzerland,SUI,2010,Vancouver,Cross Country Skiing,Cross Country Skiing Men's 15 kilometres,NaN
42202,93098,Paul Constantin Pepene,M,21.0,174.0,68.0,Romania,ROU,2010,Vancouver,Cross Country Skiing,Cross Country Skiing Men's 30 km Skiathlon,NaN
40102,33650,Vesna Fabjan,F,24.0,170.0,62.0,Slovenia,SLO,2010,Vancouver,Cross Country Skiing,Cross Country Skiing Women's Team Sprint,NaN

In [45]:
## sort city z-a
dfw.sort_values(by="City", ascending = False)

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal
39561,11951,Ole Einar Bjrndalen,M,36.0,178.0,65.0,Norway,NOR,2010,Vancouver,Biathlon,Biathlon Men's 4 x 7.5 kilometres Relay,Gold
40747,52463,Marc Iselin,M,29.0,178.0,83.0,Switzerland,SUI,2010,Vancouver,Snowboarding,Snowboarding Men's Parallel Giant Slalom,NaN
40741,52316,Dmitry Gennadyevich Ipatov,M,25.0,176.0,60.0,Russia,RUS,2010,Vancouver,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN
40742,52345,"Michael James Grant ""Mike"" Ireland",M,36.0,181.0,79.0,Canada,CAN,2010,Vancouver,Speed Skating,Speed Skating Men's 500 metres,NaN
40743,52392,Haley Lyn Irwin,F,21.0,170.0,78.0,Canada,CAN,2010,Vancouver,Ice Hockey,Ice Hockey Women's Ice Hockey,Gold
...,...,...,...,...,...,...,...,...,...,...,...,...,...
22495,75068,Dennis Edward Marineau,M,29.0,172.0,81.0,Canada-2,CAN,1992,Albertville,Bobsleigh,Bobsleigh Men's Two,NaN
22494,74979,Diego Margozzini,M,21.0,182.0,76.0,Chile,CHI,1992,Albertville,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN
22493,74960,Pascal Margerit,M,20.0,180.0,75.0,France,FRA,1992,Albertville,Ice Hockey,Ice Hockey Men's Ice Hockey,NaN
22492,74931,Alexander Marent,M,22.0,168.0,68.0,Austria,AUT,1992,Albertville,Cross Country Skiing,Cross Country Skiing Men's 4 x 10 kilometres R...,NaN
21917,53932,Pawe Julian Jaroszek,M,20.0,185.0,82.0,Poland,POL,1992,Albertville,Speed Skating,"Speed Skating Men's 1,500 metres",NaN

## Sorting by multiple values

```dataframe.sort_values(by=["Value 1", "Value 2"], ascending = True)``` for A-Z or smaller numbers to bigger numbers

```ascending = False``` for Z-A or bigger to smaller numbers.

In [46]:
## Sort by values (City and Year) for winter olympics
dfw.sort_values(by=["Year", "City"])

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal
0,391,Clarence John Abel,M,23.0,185.0,102.0,United States,USA,1924,Chamonix,Ice Hockey,Ice Hockey Men's Ice Hockey,Silver
1,992,Josef Adolf,M,25.0,NaN,NaN,Czechoslovakia,TCH,1924,Chamonix,Nordic Combined,Nordic Combined Men's Individual,NaN
2,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Ski Jumping,"Ski Jumping Men's Normal Hill, Individual",NaN
3,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Cross Country Skiing,Cross Country Skiing Men's 18 kilometres,NaN
4,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Nordic Combined,Nordic Combined Men's Individual,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
48559,135485,Stepan Olegovich Zuyev,M,25.0,189.0,90.0,Russia,RUS,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN
48560,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN
48561,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN
48562,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN
48563,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN

In [47]:
## sort by year and then city

# Should Winter and Summer data remain separate?

### What if we want to know total gold medals for any country?

### But if we combine them, how to we easily distinguish between summer and winter?

In [48]:
dfs.info()

<class 'pandas.DataFrame'>
RangeIndex: 222552 entries, 0 to 222551
Data columns (total 13 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   ID            222552 non-null  int64
 1   Athlete Name  222552 non-null  str
 2   Sex           222552 non-null  str
 3   Age           213363 non-null  float64
 4   Height        170695 non-null  float64
 5   Weight        168698 non-null  float64
 6   Team          222552 non-null  str
 7   NOC           222552 non-null  str
 8   Year          222552 non-null  int64
 9   City          222552 non-null  str
 10  Sport         222552 non-null  str
 11  Event         222552 non-null  str
 12  Medal         34088 non-null   str
dtypes: float64(3), int64(2), str(8)
memory usage: 22.1 MB

### Creating a new column with a default value

In [49]:
## In the summer dataframe, add "Season" column with the value "Summer"
dfs["Season"] = "summer"
dfs.head()

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
0,1724,Aristidis Akratopoulos,M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Tennis,Tennis Men's Singles,NaN,summer
1,1724,Aristidis Akratopoulos,M,NaN,NaN,NaN,Greece-3,GRE,1896,Athina,Tennis,Tennis Men's Doubles,NaN,summer
2,1725,"Konstantinos ""Kostas"" Akratopoulos",M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Tennis,Tennis Men's Singles,NaN,summer
3,1725,"Konstantinos ""Kostas"" Akratopoulos",M,NaN,NaN,NaN,Greece-3,GRE,1896,Athina,Tennis,Tennis Men's Doubles,NaN,summer
4,4113,Anastasios Andreou,M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Athletics,Athletics Men's 110 metres Hurdles,NaN,summer

In [50]:
## In the winter dataframe, add "Season" column with the value "Winter"
dfw["Season"] = "winter"

In [51]:
dfw.head()

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
0,391,Clarence John Abel,M,23.0,185.0,102.0,United States,USA,1924,Chamonix,Ice Hockey,Ice Hockey Men's Ice Hockey,Silver,winter
1,992,Josef Adolf,M,25.0,NaN,NaN,Czechoslovakia,TCH,1924,Chamonix,Nordic Combined,Nordic Combined Men's Individual,NaN,winter
2,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Ski Jumping,"Ski Jumping Men's Normal Hill, Individual",NaN,winter
3,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Cross Country Skiing,Cross Country Skiing Men's 18 kilometres,NaN,winter
4,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Nordic Combined,Nordic Combined Men's Individual,NaN,winter

In [52]:
## One equal sign is an assignment. 
x = 10
x

10

In [53]:
## Two equal signs are checking for equality. 
x == 12

False

In [54]:
x == 10

True

In [55]:
dfw.columns

Index(['ID', 'Athlete Name', 'Sex', 'Age', 'Height', 'Weight', 'Team', 'NOC',
       'Year', 'City', 'Sport', 'Event', 'Medal', 'Season'],
      dtype='str')

In [56]:
## are the two column headers identical?
dfw.columns ==  dfs.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [57]:
## join winter and summer dataframes together into a dataframe called df
# df = pd.concat([dfs,dfw]) ## Led to the wrong total index. 
df = pd.concat([dfs,dfw], ignore_index = True)
df

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
0,1724,Aristidis Akratopoulos,M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Tennis,Tennis Men's Singles,NaN,summer
1,1724,Aristidis Akratopoulos,M,NaN,NaN,NaN,Greece-3,GRE,1896,Athina,Tennis,Tennis Men's Doubles,NaN,summer
2,1725,"Konstantinos ""Kostas"" Akratopoulos",M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Tennis,Tennis Men's Singles,NaN,summer
3,1725,"Konstantinos ""Kostas"" Akratopoulos",M,NaN,NaN,NaN,Greece-3,GRE,1896,Athina,Tennis,Tennis Men's Doubles,NaN,summer
4,4113,Anastasios Andreou,M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Athletics,Athletics Men's 110 metres Hurdles,NaN,summer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271111,135485,Stepan Olegovich Zuyev,M,25.0,189.0,90.0,Russia,RUS,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN,winter
271112,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN,winter
271113,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN,winter
271114,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN,winter
271115,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN,winter

In [58]:
some_val = "dfw"
another_val = "dfs"

In [59]:
some_val + another_val

'dfwdfs'

In [60]:
"some_val" + "another_val"

'some_valanother_val'

In [61]:
### confirm that you have the correct number of rows after the join.
### you can scroll up to count the number of entries in oly_w and oly_s.
### The totals should be equal to the value generated below

# Query to subset

Create smaller datasets with only the information you want

### Create a subset that holds the results from the Sochi Olympics

```df.query("ColumnName == 'some_value'")```

In [62]:
## return df that holds only Sochi data

df.query("City == 'Sochi' ")

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
266225,16,Juhamatti Tapio Aaltonen,M,28.0,184.0,85.0,Finland,FIN,2014,Sochi,Ice Hockey,Ice Hockey Men's Ice Hockey,Bronze,winter
266226,126,Forough Abbasi,F,20.0,164.0,58.0,Iran,IRI,2014,Sochi,Alpine Skiing,Alpine Skiing Women's Slalom,NaN,winter
266227,145,Jeremy Abbott,M,28.0,175.0,70.0,United States,USA,2014,Sochi,Figure Skating,Figure Skating Men's Singles,NaN,winter
266228,145,Jeremy Abbott,M,28.0,175.0,70.0,United States,USA,2014,Sochi,Figure Skating,Figure Skating Mixed Team,Bronze,winter
266229,463,Agnese boltia,F,17.0,166.0,60.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Women's Super G,NaN,winter
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271111,135485,Stepan Olegovich Zuyev,M,25.0,189.0,90.0,Russia,RUS,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN,winter
271112,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN,winter
271113,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN,winter
271114,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN,winter
271115,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN,winter

In [63]:
df.query("Sport == 'Ice Hockey' ")

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
12651,5429,Karl Wilhelm Konrad Arwe (Andersson-),M,22.0,NaN,NaN,Sweden,SWE,1920,Antwerpen,Ice Hockey,Ice Hockey Men's Ice Hockey,NaN,summer
12775,10216,"Robert John ""Bobby"" Benson",M,25.0,167.0,61.0,Canada,CAN,1920,Antwerpen,Ice Hockey,Ice Hockey Men's Ice Hockey,Gold,summer
12916,13265,"Raymond Leroy ""Ray"" Bonney",M,28.0,175.0,81.0,United States,USA,1920,Antwerpen,Ice Hockey,Ice Hockey Men's Ice Hockey,Silver,summer
13075,16648,Hjalmar Eric Wilhelm Burman,M,22.0,NaN,NaN,Sweden,SWE,1920,Antwerpen,Ice Hockey,Ice Hockey Men's Ice Hockey,NaN,summer
13085,17100,"Jacob Walter ""Wally"" Byron",M,35.0,180.0,65.0,Canada,CAN,1920,Antwerpen,Ice Hockey,Ice Hockey Men's Ice Hockey,Gold,summer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270998,133605,Tom Zborsk,M,26.0,183.0,88.0,Slovakia,SVK,2014,Sochi,Ice Hockey,Ice Hockey Men's Ice Hockey,NaN,winter
271043,134391,Carl Henrik Zetterberg,M,33.0,183.0,86.0,Sweden,SWE,2014,Sochi,Ice Hockey,Ice Hockey Men's Ice Hockey,Silver,winter
271080,134924,Marek idlick,M,37.0,180.0,85.0,Czech Republic,CZE,2014,Sochi,Ice Hockey,Ice Hockey Men's Ice Hockey,NaN,winter
271100,135255,Julia Zorn,F,24.0,170.0,73.0,Germany,GER,2014,Sochi,Ice Hockey,Ice Hockey Women's Ice Hockey,NaN,winter
271108,135365,Mats Andr Zuccarello-Aasen,M,26.0,171.0,74.0,Norway,NOR,2014,Sochi,Ice Hockey,Ice Hockey Men's Ice Hockey,NaN,winter

### Note the order of the single and double quotes:

If you open with double quotes, the inner quotes have to be single quotes:

```df.query("City == 'Sochi'")```

If you open with single quotes, the inner quotes have to be double quotes:

```df.query('City == "Sochi"')```


Using the same outer and inner quotes will break your code:
</br>
```df.query("City == "Sochi"") ## will break ```

In [64]:
## Store subset into dataframe called sochi_df

**Syntax for querying multi-word column names:**

```dataframe.query('`column name` comparison_operator value')```

Note the opening and closing tick marks ``` ` ```

In [65]:
#will break
df.query("`Athlete Name` == 'Jeremy Abbott'")

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
91003,146,Jeremy Abbott,M,19.0,179.0,71.0,Canada,CAN,1976,Montreal,Canoeing,"Canoeing Men's Canadian Doubles, 1,000 metres",NaN,summer
261824,145,Jeremy Abbott,M,24.0,175.0,70.0,United States,USA,2010,Vancouver,Figure Skating,Figure Skating Men's Singles,NaN,winter
266227,145,Jeremy Abbott,M,28.0,175.0,70.0,United States,USA,2014,Sochi,Figure Skating,Figure Skating Men's Singles,NaN,winter
266228,145,Jeremy Abbott,M,28.0,175.0,70.0,United States,USA,2014,Sochi,Figure Skating,Figure Skating Mixed Team,Bronze,winter

In [66]:
## query to return on french athletes

## Query by dates

You'll learn more about date and time in the coming week. For now, please note how the ```Year``` column is a  ```int64``` object and NOT a ```datetime``` object. We can still work with it for our needs.

In [67]:
## GET INFO

In [68]:
## Find all the 1900 competitions
df.query("Year == 1900")

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
380,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,summer
381,133,Franz Abb,M,NaN,NaN,NaN,Germany,GER,1900,Paris,Gymnastics,Gymnastics Men's Individual All-Around,NaN,summer
382,150,Margaret Ives Abbott (-Dunne),F,23.0,NaN,NaN,United States,USA,1900,Paris,Golf,Golf Women's Individual,Gold,summer
383,151,Mary Perkins Ives Abbott (Perkins-),F,42.0,NaN,NaN,United States,USA,1900,Paris,Golf,Golf Women's Individual,NaN,summer
384,404,"Louis Grenville ""Lou"" Abell",M,15.0,NaN,NaN,Vesper Boat Club,USA,1900,Paris,Rowing,Rowing Men's Coxed Eights,Gold,summer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2311,131733,William Hayden Wright,M,NaN,NaN,NaN,A North American Team,USA,1900,Paris,Polo,Polo Men's Polo,Bronze,summer
2312,133574,Henri Yvon,M,NaN,NaN,NaN,France,FRA,1900,Paris,Fencing,"Fencing Men's Foil, Masters, Individual",NaN,summer
2313,133574,Henri Yvon,M,NaN,NaN,NaN,France,FRA,1900,Paris,Fencing,"Fencing Men's epee, Masters, Individual",NaN,summer
2314,133807,Pyotr Antonovich Zakovorot,M,NaN,NaN,NaN,Russia,RUS,1900,Paris,Fencing,"Fencing Men's Sabre, Masters, Individual",NaN,summer
2315,134198,"Walter John ""Jack"" Zealley",M,NaN,NaN,NaN,Upton Park FC,GBR,1900,Paris,Football,Football Men's Football,Gold,summer

In [69]:
df.query("Year  == 1936 & NOC == 'USA'")

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
30008,762,"Gordon Belgum ""Gordy"" Adam",M,21.0,NaN,NaN,United States,USA,1936,Berlin,Rowing,Rowing Men's Coxed Eights,Gold,summer
30012,829,"Morgan Orlando Adams, Jr.",M,20.0,NaN,NaN,Mystery,USA,1936,Berlin,Sailing,Sailing Mixed 6 metres,NaN,summer
30036,1339,William Alexander (Wilhelm Alexander-) Ahlemeyer,M,29.0,NaN,NaN,United States,USA,1936,Berlin,Handball,Handball Men's Handball,NaN,summer
30054,2387,"David Donald ""Dave"" Albritton",M,23.0,191.0,79.0,United States,USA,1936,Berlin,Athletics,Athletics Men's High Jump,Silver,summer
30063,2552,Hugh Vincenzo Alessandroni,M,28.0,NaN,NaN,United States,USA,1936,Berlin,Fencing,"Fencing Men's Foil, Individual",NaN,summer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
224784,128832,"Alan Morgan ""Al"" Washbond",M,36.0,NaN,NaN,United States-1,USA,1936,Garmisch-Partenkirchen,Bobsleigh,Bobsleigh Men's Two,Gold,winter
224785,128834,"Albert Lincoln ""Link"" Washburn",M,24.0,NaN,NaN,United States,USA,1936,Garmisch-Partenkirchen,Alpine Skiing,Alpine Skiing Men's Combined,NaN,winter
224793,129326,Estelle D. Weigel (-Schmitt),F,21.0,NaN,NaN,United States,USA,1936,Garmisch-Partenkirchen,Figure Skating,Figure Skating Women's Singles,NaN,winter
224794,129328,Louise E. Weigel (-Atwill),F,23.0,NaN,NaN,United States,USA,1936,Garmisch-Partenkirchen,Figure Skating,Figure Skating Women's Singles,NaN,winter
224814,131578,"Elizabeth Davenport ""Betty"" Woolsey",F,27.0,NaN,NaN,United States,USA,1936,Garmisch-Partenkirchen,Alpine Skiing,Alpine Skiing Women's Combined,NaN,winter

In [70]:
india_df = df.query("NOC == 'IND'")
india_df

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
1824,97066,Norman Gilbert Pritchard (-Trevor),M,24.0,NaN,NaN,India,IND,1900,Paris,Athletics,Athletics Men's 60 metres,NaN,summer
1825,97066,Norman Gilbert Pritchard (-Trevor),M,24.0,NaN,NaN,India,IND,1900,Paris,Athletics,Athletics Men's 100 metres,NaN,summer
1826,97066,Norman Gilbert Pritchard (-Trevor),M,24.0,NaN,NaN,India,IND,1900,Paris,Athletics,Athletics Men's 200 metres,Silver,summer
1827,97066,Norman Gilbert Pritchard (-Trevor),M,24.0,NaN,NaN,India,IND,1900,Paris,Athletics,Athletics Men's 110 metres Hurdles,NaN,summer
1828,97066,Norman Gilbert Pritchard (-Trevor),M,24.0,NaN,NaN,India,IND,1900,Paris,Athletics,Athletics Men's 200 metres Hurdles,Silver,summer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263565,58899,Shiva Keshavan,M,28.0,183.0,85.0,India,IND,2010,Vancouver,Luge,Luge Men's Singles,NaN,winter
264127,72364,Tashi Lundup,M,25.0,175.0,74.0,India,IND,2010,Vancouver,Cross Country Skiing,Cross Country Skiing Men's 15 kilometres,NaN,winter
264481,84450,Jamyang Namgial,M,24.0,170.0,71.0,India,IND,2010,Vancouver,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN,winter
267971,52325,Nadeem Iqbal,M,30.0,173.0,65.0,India,IND,2014,Sochi,Cross Country Skiing,Cross Country Skiing Men's 15 kilometres,NaN,winter
270515,119471,Himanshu Thakur,M,20.0,167.0,54.0,India,IND,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN,winter

In [71]:
india_df.query("Medal == 'Gold' or Medal == 'Silver' or Medal == 'Bronze' " ).sort_values(by="Medal")

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
82464,23098,Charles Cornelius,M,26.0,170.0,65.0,India,IND,1972,Munich,Hockey,Hockey Men's Hockey,Bronze,summer
46062,53275,Khashaba Dadasaheb Jahdav,M,25.0,NaN,NaN,India,IND,1952,Helsinki,Wrestling,"Wrestling Men's Bantamweight, Freestyle",Bronze,summer
79218,111075,Jagjit Singh Kular,M,24.0,170.0,58.0,India,IND,1968,Mexico City,Hockey,Hockey Men's Hockey,Bronze,summer
79222,111123,Prithipal Singh,M,36.0,175.0,71.0,India,IND,1968,Mexico City,Hockey,Hockey Men's Hockey,Bronze,summer
79225,111156,Tarsem Singh Kular,M,21.0,173.0,66.0,India,IND,1968,Mexico City,Hockey,Hockey Men's Hockey,Bronze,summer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63008,111083,Jaswant Singh,M,29.0,185.0,77.0,India,IND,1960,Roma,Hockey,Hockey Men's Hockey,Silver,summer
63014,111159,Udham Singh Kular,M,32.0,168.0,58.0,India,IND,1960,Roma,Hockey,Hockey Men's Hockey,Silver,summer
63019,111173,Raghbir Singh Bhola,M,33.0,183.0,67.0,India,IND,1960,Roma,Hockey,Hockey Men's Hockey,Silver,summer
56517,4518,"Joseph Anthony ""Joe"" Antic",M,29.0,168.0,59.0,India,IND,1960,Roma,Hockey,Hockey Men's Hockey,Silver,summer
1826,97066,Norman Gilbert Pritchard (-Trevor),M,24.0,NaN,NaN,India,IND,1900,Paris,Athletics,Athletics Men's 200 metres,Silver,summer

In [72]:
india_medals["Medal"].unique()

NameError: name 'india_medals' is not defined

In [ ]:
### return all the competitions between 1940 and 1960 (inclusive)
df.query("1940 <= Year <= 1960 ")

In [ ]:
## Were there any games in the 1940s?

In [ ]:
## return only Tennis competitions between 1920 and 1950 (inclusive)

In [ ]:
## return only Women's Tennis competitions results
## between 1996 and 2018 inclusive

In [ ]:
## volleyball or rowing for only Male

In [80]:
##Homework Challenge
##How many medals were handed out in winter games v. summer game (return both in absolutes and as a percentage)?¶
dfw.info
dfw.sort_values(by="Medal")

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
24437,18813,Karen Cashman (-Lehmann),F,22.0,165.0,61.0,United States,USA,1994,Lillehammer,Short Track Speed Skating,"Short Track Speed Skating Women's 3,000 metres...",Bronze,winter
13643,106605,Erich Schrer,M,29.0,173.0,82.0,Switzerland-1,SUI,1976,Innsbruck,Bobsleigh,Bobsleigh Men's Two,Bronze,winter
13639,106512,Franz Schachner,M,25.0,176.0,83.0,Austria-1,AUT,1976,Innsbruck,Luge,Luge Mixed (Men)'s Doubles,Bronze,winter
13627,106216,Sergey Petrovich Savelyev,M,27.0,178.0,70.0,Soviet Union,URS,1976,Innsbruck,Cross Country Skiing,Cross Country Skiing Men's 4 x 10 kilometres R...,Bronze,winter
33950,107003,Andreas Schltter,M,29.0,185.0,75.0,Germany,GER,2002,Salt Lake City,Cross Country Skiing,Cross Country Skiing Men's 4 x 10 kilometres R...,Bronze,winter
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48559,135485,Stepan Olegovich Zuyev,M,25.0,189.0,90.0,Russia,RUS,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN,winter
48560,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN,winter
48561,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN,winter
48562,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN,winter
48563,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN,winter

dfw['Medal'].value_counts()

In [103]:
dfw['Medal'].value_counts(normalize = True) * 100, 2

(Medal
 Gold      33.590869
 Silver    33.292362
 Bronze    33.116769
 Name: proportion, dtype: float64,
 2)

In [106]:
dfs['Medal'].value_counts()

Medal
Gold      11459
Bronze    11409
Silver    11220
Name: count, dtype: int64

In [107]:
dfw['Medal'].value_counts()

Medal
Gold      1913
Silver    1896
Bronze    1886
Name: count, dtype: int64

In [87]:
dfs['Medal'].value_counts(normalize = True) * 100, 2

(Medal
 Gold      33.615935
 Bronze    33.469256
 Silver    32.914809
 Name: proportion, dtype: float64,
 2)

In [101]:
top10_gold = (
    dfs[dfs['Medal'] == 'Gold']         # filter to gold medals only
    .groupby('Team')                    # group by team
    .size()                             # count gold medals per team
    .reset_index(name='count')          # flatten into a DataFrame
    .sort_values('count',               # sort descending
                 ascending=False)
    .head(10)                           # take top 10 teams
    .reset_index(drop=True)             # clean up index
)

# Calculate percentage of gold medals each country holds out of the top 10 total
top10_gold['percentage'] = (
    top10_gold['count'] / top10_gold['count'].sum() * 100
).round(2)

print(top10_gold)

            Team  count  percentage
0  United States   2333       35.61
1   Soviet Union    830       12.67
2        Germany    564        8.61
3          Italy    492        7.51
4  Great Britain    481        7.34
5        Hungary    432        6.59
6         France    421        6.43
7   East Germany    337        5.14
8      Australia    336        5.13
9         Sweden    326        4.98

### How many values in a column?

## Counting

-  ```sum``` adds up all the values in a dataset, to give you the total amount.

-  ```count``` tells you how many items of particular values exist in a dataset. It doesn't care about the values themselves, just the number of entries.

So if you have the following of donations by individuals:

| Donor | Amt   |
|-------|-------|
| A     | 200   |
| A     | 200   |
| B     | 300   |
| B     | 100   |
| A     | 200   |
| A     | 100   |


- The ```sum``` of donations is: 1,100
- The ```count``` of donations is: 6

The ```count``` of donors is:
- ```A appears 4```
- ```B appears 2```

The count of amounts:
- ```contribs of 200 were given 3 times```,
- ```contribs of 100 were given 2 times```,
- ```contribs of 300 were given 1 times```



We use the ```.value_counts()``` method:

```df_name["column_name"].value_counts()```

In [ ]:
## bring in our diamonds dataset
diamonds_df = pd.read_csv("https://raw.githubusercontent.com/sandeepmj/datasets/refs/heads/main/diamonds.csv")
diamonds_df

In [ ]:
## number of unique cuts
diamonds_df["diamond cut"].nunique()

In [ ]:
diamonds_df["diamond cut"].value_counts(ascending = True)

In [ ]:
diamonds_df["diamond cut"].value_counts(ascending = False).to_frame("Quantity")

In [ ]:
## what is the break down diamond_cut
diamonds_df["diamond cut"].value_counts().to_frame("Quantity").sort_values(by="Quantity", ascending = True)

### ```value_counts()``` parameter

By default, it is ```.value_counts(normalize = False)```

This gives you want we calculated above

But ```.value_counts(normalize = True)``` returns  proportions (fractions of the total).

In [ ]:
## get as proportion
diamonds_df["diamond cut"].value_counts(normalize = True)

## Round it

```round(item_to_round, number_of_decimal_places)```

In [ ]:
## return as percentage, rounded 2 decimal place
round(diamonds_df["diamond cut"].value_counts(normalize = True) * 100, 2)

## Homework Challenge

#### 1. How many medals were handed out in winter games v. summer game (return both in absolutes and as a percentage)?

#### 2. Top 10 count of gold medals by country

#### 3. Of these top 10, what percent of the gold medals do they have?